### ISSUE TITLE
Airflow deployment message in NOTES.txt template are not consistent with the latest location for the chart name

### ISSUE THREAD

**Issue by pgerbino** [bitnami/azure-marketplace-charts#10]
Line 46 of NOTES.txt under bitnami\airflow\templates shows shows the upgrade command as

helm upgrade {{.Release.Name}} **bitnami**/{{ .Chart.Name}} \

I believe it should be 

helm upgrade {{.Release.Name}} **bitnami-azure**/{{ .Chart.Name}} \

**Comment by carrodher** [comment]
Thanks! I will create a PR fixing it

**Comment by beltran-rubo** [comment]
Thanks for reporting it. The name of the repo is something the user can configure this on his own and there is not any variable available in Helm to support this. E.g. `helm repo add my-repo http://URL` so the instruction should be `helm upgrade {{.Release.Name}} my-repo/{{ .Chart.Name}}`

We consider that instruction just using an example (the "bitnami" repo name) but it could be a different name like "bitnami-azure" or any different one.
