### ISSUE TITLE
Deployment instructions need clarification

### ISSUE THREAD

**Issue by pgerbino** [bitnami/azure-marketplace-charts#11]
If I create an airflow installation using Git the necessary sidecars and volumes are created **but** the supplied upgrade command is incomplete when upgrading as it does not include the necessary git properties. I realise this could have simply been my mistake but it may well be clearer to highlight in the upgrade command that the git properties must also be included otherwise mystery will abound as to why the git sync isn't working. Thanks.

For completeness I included the following in both the install and upgrade commands and it worked:

airflow.cloneDagFilesFromGit.enabled=true
airflow.cloneDagFilesFromGit.repository=https://github.com/USERNAME/REPOSITORY
airflow.cloneDagFilesFromGit.branch=master
airflow.cloneDagFilesFromGit.interval=60

**Comment by carrodher** [comment]
Thanks for letting us know, I will create a PR to improve this command documentation

**Comment by carrodher** [comment]
Hi, just to let you know that we added some instructions related to DAG files in this section of the README: https://github.com/bitnami/azure-marketplace-charts/blob/master/bitnami/airflow/README.md#option-3-get-your-dag-files-from-a-git-repository

Thanks for reporting it!
