### ISSUE TITLE
Attempting to use the airflow helm chart but the helm repo does not have the required YAML file

### ISSUE THREAD

**Issue by pgerbino** [bitnami/azure-marketplace-charts#9]

**Comment by pgerbino** [comment]
Attempting to follow the instructions on https://github.com/bitnami/azure-marketplace-charts/tree/master/bitnami/airflow

`xxxx@Azure:~$ helm repo add bitnami-azure https://marketplace.azurecr.io
Error: Looks like "https://marketplace.azurecr.io" is not a valid chart repository or cannot be reached: Failed to fetch https://marketplace.azurecr.io/index.yaml : 404 Not Found`

**Comment by carrodher** [comment]
Hi @pgerbino thanks for report the issue.

It seems that this section in the README inside each chart folder is not updated, can you use this command?
```
helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
```

This is the instruction that appears in the main README (the one present in the root of the repository). I just created an internal task to fix all the chart READMEs.
Thanks again!

**Comment by pgerbino** [comment]
Thanks @carrodher - I followed the top level link and successfully installed Airflow on AKS.
